### ISSUE TITLE
I cannot commit to this repo

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSUBD2K/BDK14-Ontologies-101#1]
I get this error message:
"Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository."

Can someone help?
@biodevlab @bjorn-pederson-ohsu

**Comment by bjornpederson** [comment]
After looking around, I believe this has to be addressed by the owner (@biodevlab)

https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by nicolevasilevsky** [comment]
Thanks @bjorn-pederson-ohsu!

**Comment by nicolevasilevsky** [comment]
I'm all set now, thanks!
